---
- hosts: "{{hosts}}"
  gather_facts: True
  strategy: free
  become_user: "{{ USERS }}"
  vars_files:
    - ../../../vars/credentials.anvars
    - ../../../vars/docker-image.yml
  tasks:
    - name: "Login aws ECR"
      shell: "{{ item }}"
      with_items:    
        - $(aws ecr get-login --no-include-email --region {{AWS_DEFAULT_REGION}})
      become_user: "{{ USERS }}"

    - name: "Pull default Docker image"
      shell: "{{ item }}"
      with_items:    
        - docker pull {{IMAGE_NGINX_PATH_DEV}}
      become_user: "{{ USERS }}"
      when: '"{{env}}" == "DEV"'

    - name: "Pull default Docker image"
      shell: "{{ item }}"
      with_items:    
        - docker pull {{IMAGE_NGINX_PATH_PRD}}
      become_user: "{{ USERS }}"
      when: '"{{env}}" == "PRD"'

    - name: "Run docker image"
      shell: "{{ item }}"
      with_items:    
        - docker run -e BUCKET_NAME={{BUCKET_DEV}} -e AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}} -e AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}} -e AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}} -p 80:8081 -p 443:443 --restart always -d {{IMAGE_NGINX_PATH_DEV}}
      when: '"{{env}}" == "DEV"'

    - name: "Run docker image"
      shell: "{{ item }}"
      with_items:    
        - docker run -e BUCKET_NAME={{BUCKET_PRD}} -e AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}} -e AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}} -e AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}} -p 80:8081 -p 443:443 --restart always -d {{IMAGE_NGINX_PATH_PRD}}
      when: '"{{env}}" == "PRD"'
    
